### ISSUE TITLE
Released package has missing files.

### ISSUE THREAD

**Issue by saumitrabhave** [neighborhood999/react-gh-like-diff#118]
Package.json define `"main": "lib/react-gh-like-diff.cjs.js"` but there is no such file in the released packge. Can you please fix the issue and update NPM package.

**Comment by neighborhood999** [comment]
That's weird, I will fix this issue.

If you need to use, you can downgrade to 1.0.5.

**Comment by neighborhood999** [comment]
Hi @saumitrabhave 

I already bump package to `1.0.7` version, please check and try it, thank you.
