### ISSUE TITLE
Can I use this library in my enterprise company project 

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [neighborhood999/react-gh-like-diff#129]
Here I am looking for few details -

Can I use this library in my enterprise company project ? I can see this is under MIT license so I think I can use it.

Can I assume this is stable component and we can refer and use in our project ?

Thanks for awesome library and work, looking forward to hear from you. Thanks.

**Comment by neighborhood999** [comment]
Yes, you can use it, but I think you should discuss with your legal team for this because this library depends on other libraries.
