### ISSUE TITLE
how to scroll both panes in side-by-side?

### ISSUE THREAD

**Issue by hungdev** [neighborhood999/react-gh-like-diff#133]
Thank for a quick response on #131  @neighborhood999 
I saw `synchronisedScroll` option props in [diff2html option](https://github.com/rtfpessoa/diff2html#configuration), but i didnt see effect when i added that props to options.
here my code:
```
<ReactGhLikeDiff
            options={{
              inputFormat: 'diff',
              outputFormat: 'side-by-side',
              originalFileName: 'File',
              updatedFileName: 'File',
              synchronisedScroll: true,
            }}
            past={oldCode}
            current={newCode}
          />
```

thank you.

**Comment by neighborhood999** [comment]
Yep, the `synchronisedScroll` is not supported, because our [defautOptions](https://github.com/neighborhood999/react-gh-like-diff/blob/b0c525785e18ffb7e6622be39175e8640ed8519d/src/utils.js#L9-L18) like:

```js
export const defaultOptions = {
  originalFileName: 'Unknown-File-Name',
  updatedFileName: 'Unknown-File-Name',
  inputFormat: 'diff',
  outputFormat: 'side-by-side',
  showFiles: false,
  matching: 'none',
  matchWordsThreshold: 0.25,
  matchingMaxComparisons: 2500
};
```

If I have more free time I will add this, but PRs is welcome.

**Comment by neighborhood999** [comment]
I go to diff2html docs to confirm `synchronisedScroll` this option, it belongs to `Diff2HtmlUI` this helper, not the `Diff2Html`, so we can't support for this option.
