### ISSUE TITLE
Component won't rerender while changing options props

### ISSUE THREAD

**Issue by GBcrimson** [neighborhood999/react-gh-like-diff#173]
`react-gh-like-diff/src/index.js` here options PropTypes knowingly set to avoid rerendering. Could you add it to onlyUpdateForPropTypes setPropTypes?

**Comment by neighborhood999** [comment]
Did you mean?

https://github.com/neighborhood999/react-gh-like-diff/blob/955b8c91b561b330dc4641649e396a9c18e75d13/src/index.js#L25-L30

**Comment by GBcrimson** [comment]
Yes

**Comment by GBcrimson** [comment]
If I want to change view from side-by-side to line-by-line(or vice versa) by clicking one button at parent's component, I'll wait to rerender this with other outputFormat. However, it's not

**Comment by neighborhood999** [comment]
I will try to fix this, but PRs welcome.

**Comment by GBcrimson** [comment]
`setPropTypes({ 
   past: PropTypes.string, 
   current: PropTypes.string, 
   options: PropTypes.object, 
   diffString: PropTypes.string 
 }), ` something like this

**Comment by GBcrimson** [comment]
https://github.com/neighborhood999/react-gh-like-diff/pull/174 I think, that's enough

**Comment by neighborhood999** [comment]
I published the 1.1.1 version as soon as possible, thank you.

https://github.com/neighborhood999/react-gh-like-diff/releases/tag/1.1.1
