### ISSUE TITLE
1.1.4 introduced breaking change

### ISSUE THREAD

**Issue by HarshaLaxman** [neighborhood999/react-gh-like-diff#241]
https://github.com/neighborhood999/react-gh-like-diff/commit/2636fca0019501043213f2324754b56299b35a96#diff-ff6e5f22a9c7e66987b19c0199636480

`import 'react-gh-like-diff/lib/diff2html.css';`
breaks in any application using this package

Thank you! Very useful tool.

**Comment by neighborhood999** [comment]
> [2636fca#diff-ff6e5f22a9c7e66987b19c0199636480](https://github.com/neighborhood999/react-gh-like-diff/commit/2636fca0019501043213f2324754b56299b35a96#diff-ff6e5f22a9c7e66987b19c0199636480)
> 
> `import 'react-gh-like-diff/lib/diff2html.css';`
> breaks in any application using this package
> 
> Thank you! Very useful tool.

Sorry my bad, I forgot this breaking changed!

I will bump new version and upated.

**Comment by neighborhood999** [comment]
Update README and [release](https://github.com/neighborhood999/react-gh-like-diff/releases) for how to import css style.

Thank you!
