### ISSUE TITLE
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.

### ISSUE THREAD

**Issue by tlrdstd** [neighborhood999/react-gh-like-diff#298]
Including version 2.0.2 of this component in my React 16.13.1 project renders the following warning in my Chrome dev tools:

```
const { ReactGhLikeDiff } = require("react-gh-like-diff");
```

```
> Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
  | printWarning | @ | react-gh-like-diff.esm.js:formatted:1
-- | -- | -- | --
  | warn | @ | react-gh-like-diff.esm.js:formatted:1
  | createFactoryWithValidation | @ | react-gh-like-diff.esm.js:formatted:1
  | (anonymous) | @ | react-gh-like-diff.esm.js:formatted:1
  | (anonymous) | @ | react-gh-like-diff.esm.js:formatted:1
  | onlyUpdateForPropTypes | @ | react-gh-like-diff.esm.js:formatted:1
  | (anonymous) | @ | react-gh-like-diff.esm.js:formatted:1
  | (anonymous) | @ | react-gh-like-diff.esm.js:formatted:1
  | (anonymous) | @ | react-gh-like-diff.esm.js:formatted:1
  | ./node_modules/react-gh-like-diff/dist/js/react-gh-like-diff.esm.js | @ | react-gh-like-diff.esm.js:formatted:1
  | __webpack_require__ | @ | bootstrap:784
  | fn | @ | bootstrap:150
...
```

React documentation for the error: https://reactjs.org/warnings/legacy-factories.html

Note that I'm not actually even attempting to render this component yet. I've only loaded it into my Typescript project via `require()` as shown above, and that error appears.

**Comment by neighborhood999** [comment]
This error message coming from recompose.

ref: https://github.com/acdlite/recompose/pull/795

**Comment by tlrdstd** [comment]
Looks like recompose is a dead project. Any plan to switch to one of the forks in that bug ticket that fix the issue?

Or, per https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018 , refactoring this package to use modern React hooks?

**Comment by neighborhood999** [comment]
I think refactoring this library to react hook is a good choice.

**Comment by tlrdstd** [comment]
So should this issue be reopened for tracking?
