### ISSUE TITLE
Show more context?

### ISSUE THREAD

**Issue by switz** [neighborhood999/react-gh-like-diff#81]
I'd like to see the entire string sent (using past vs. current).

Is there any way to ensure the entire file is shown?

**Comment by neighborhood999** [comment]
@switz You can setting `outputFormat` type by [configuration](https://github.com/neighborhood999/react-gh-like-diff#configuration).

The format of the output data: `line-by-line` or `side-by-side`.

**Comment by neighborhood999** [comment]
@switz Did you mean entire file content? If true, `diff2html` doesn't support.

**Comment by neighborhood999** [comment]
If have any question, feel free reopen this issue.

**Comment by switz** [comment]
The author seems to think it relies on upstream modules https://github.com/rtfpessoa/diff2html/issues/139

**Comment by neighborhood999** [comment]
@switz `react-gh-like-diff` depend on `unifiedDiff` by `difflib`, seems need adjust `n` parameter to control context line, check out [here](https://github.com/qiao/difflib.js#unifiedDiff).

**Comment by switz** [comment]
Can you expose difflib options? If you don't have time, I can send you a PR.

**Comment by neighborhood999** [comment]
I will work for this but feel free send your PR.
